// <auto-generated />
using System;
using HealthyRecipes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthyRecipes.Data.Migrations
{
    [DbContext(typeof(HealthyRecipesDbContext))]
    [Migration("20260114173741_Added_prop_servings_to_recipe")]
    partial class Added_prop_servings_to_recipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthyRecipes.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Calories")
                        .HasColumnType("real");

                    b.Property<float?>("CarbsGoal")
                        .HasColumnType("real");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<float?>("FatGoal")
                        .HasColumnType("real");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<float?>("ProteinGoal")
                        .HasColumnType("real");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01"),
                            AccessFailedCount = 0,
                            Bio = "Fitness enthusiast",
                            Calories = 2500f,
                            CarbsGoal = 300f,
                            ConcurrencyStamp = "67a287df-fd85-4a1c-8603-fb50a54ca624",
                            CreatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "user@email.com",
                            EmailConfirmed = true,
                            FatGoal = 60f,
                            FirstName = "John",
                            Height = 180f,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EMAIL.COM",
                            NormalizedUserName = "USER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENN8Osd/COD+BNhPiVwcSRWSVLp2nqpbYCazhXnuqSertPmq3ikXhCj0IhLt1DfEVg==",
                            PhoneNumber = "0897123456",
                            PhoneNumberConfirmed = true,
                            ProteinGoal = 150f,
                            SecurityStamp = "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "user@email.com",
                            Weight = 80f
                        },
                        new
                        {
                            Id = new Guid("b4f6d2c1-3a8e-4b9c-9d0f-5a6b7c8d9e02"),
                            AccessFailedCount = 0,
                            Bio = "System administrator",
                            Calories = 2000f,
                            CarbsGoal = 250f,
                            ConcurrencyStamp = "e4a36463-b39d-4ac6-b748-4d81e8e7e8e9",
                            CreatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "admin@email.com",
                            EmailConfirmed = true,
                            FatGoal = 70f,
                            FirstName = "Anna",
                            Height = 167f,
                            LastName = "Stone",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EMAIL.COM",
                            NormalizedUserName = "ADMIN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDZoKDzNOFTI2VDaWN/Fs6od0Ie+BN4qIF2V4oopqWQRBgA56Rs8YTIG2uZISte5aw==",
                            PhoneNumber = "0897123456",
                            PhoneNumberConfirmed = true,
                            ProteinGoal = 100f,
                            SecurityStamp = "d6c5b4a3-2f1e-0d9c-8b7a-6e5f4d3c2b1a",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "admin@email.com",
                            Weight = 60f
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f4c9a61-3f9c-4e4b-8a13-91aaf29e7c01"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Name = "Main Dish",
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b61f58e9-2d69-4f4a-b1e0-4bfa1c6c3a02"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Name = "Healthy",
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c7a5d8c2-87d6-4c18-9c62-1fd9f8c73a03"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Name = "High Protein",
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d49c3a10-bd9c-4fa7-8a77-3cb62f4d0a04"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Name = "Easy & Quick",
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e7b29d63-5eaa-4e8a-9a91-9c27f5c31a05"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Name = "Meal Prep",
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CaloriesPer100g")
                        .HasColumnType("real");

                    b.Property<float>("CarbsPer100g")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("FatPer100g")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProteinPer100g")
                        .HasColumnType("real");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3b71c2a-5e3f-4d9c-9b5a-9b92d2d89e10"),
                            CaloriesPer100g = 120f,
                            CarbsPer100g = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            FatPer100g = 2.6f,
                            Name = "Chicken Breast",
                            ProteinPer100g = 22.5f,
                            Source = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2e0b6b7-9a8a-4b92-bac3-9e77a32b9c01"),
                            CaloriesPer100g = 365f,
                            CarbsPer100g = 80f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            FatPer100g = 0.7f,
                            Name = "White Rice",
                            ProteinPer100g = 7.1f,
                            Source = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f5c4b6e9-52c1-4a9e-9e15-1d7e6a2a91c2"),
                            CaloriesPer100g = 884f,
                            CarbsPer100g = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            FatPer100g = 100f,
                            Name = "Olive Oil",
                            ProteinPer100g = 0f,
                            Source = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a9cde14-1e39-4f2b-9d4c-6a3e6d01c0aa"),
                            CaloriesPer100g = 40f,
                            CarbsPer100g = 9.3f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            FatPer100g = 0.1f,
                            Name = "Onion",
                            ProteinPer100g = 1.1f,
                            Source = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b8e5b40c-44b3-4a1a-9d2f-2bb0d0e07d55"),
                            CaloriesPer100g = 149f,
                            CarbsPer100g = 33.1f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            FatPer100g = 0.5f,
                            Name = "Garlic",
                            ProteinPer100g = 6.4f,
                            Source = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.Allergy", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("b8e5b40c-44b3-4a1a-9d2f-2bb0d0e07d55"),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.CommentRating", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentRatings");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01"),
                            Comment = "Delicious and easy to prepare!",
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Rating = 5,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeCategory", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            CategoryId = new Guid("c7a5d8c2-87d6-4c18-9c62-1fd9f8c73a03"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("QuantityInGrams")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            IngredientId = new Guid("a3b71c2a-5e3f-4d9c-9b5a-9b92d2d89e10"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            QuantityInGrams = 200f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            IngredientId = new Guid("c2e0b6b7-9a8a-4b92-bac3-9e77a32b9c01"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            QuantityInGrams = 150f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            IngredientId = new Guid("f5c4b6e9-52c1-4a9e-9e15-1d7e6a2a91c2"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            QuantityInGrams = 10f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            IngredientId = new Guid("b8e5b40c-44b3-4a1a-9d2f-2bb0d0e07d55"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            QuantityInGrams = 5f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeMeal", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("RecipeMeals");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            MealId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1a2b3c4d5e6f"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            MealId = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4c3d2e1f"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.SavedMealPlan", b =>
                {
                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MealPlanId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedMealPlans");

                    b.HasData(
                        new
                        {
                            MealPlanId = new Guid("d3f9a1b2-4c5e-47a9-8b7c-0a1d2e3f4b5c"),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.SavedRecipe", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedRecipes");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01"),
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Carbs")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Fat")
                        .HasColumnType("real");

                    b.Property<Guid>("MealPlanDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanDayId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1a2b3c4d5e6f"),
                            Calories = 0f,
                            Carbs = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Fat = 0f,
                            MealPlanDayId = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            Protein = 0f,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6e5d4c3-b2a1-0f9e-8d7c-6b5a4c3d2e1f"),
                            Calories = 0f,
                            Carbs = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Fat = 0f,
                            MealPlanDayId = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            Protein = 0f,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Carbs")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Fat")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3f9a1b2-4c5e-47a9-8b7c-0a1d2e3f4b5c"),
                            Calories = 0f,
                            Carbs = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "A meal plan focused on lean muscle gain.",
                            Fat = 0f,
                            Name = "John's Lean Bulk Plan",
                            Protein = 0f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01")
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Carbs")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Fat")
                        .HasColumnType("real");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanDays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            Calories = 0f,
                            Carbs = 0f,
                            CreatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayNumber = 1,
                            DayOfWeek = 1,
                            Deleted = false,
                            Fat = 0f,
                            MealPlanId = new Guid("d3f9a1b2-4c5e-47a9-8b7c-0a1d2e3f4b5c"),
                            Protein = 0f,
                            UpdatedAt = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Carbs")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<float>("Fat")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2d6e3b9-9d5a-4b28-9c6f-8e0f3a7b6101"),
                            Calories = 0f,
                            Carbs = 0f,
                            CreatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Difficulty = 1,
                            Fat = 0f,
                            Info = "A healthy and high-protein chicken and rice bowl with sautéed onion and garlic. Perfect for meal prep and quick lunches.",
                            PrepTime = 30,
                            Protein = 0f,
                            UpdatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("e8a7c3b4-1f5d-4a6c-9b2e-7c3d5f8a9b01")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Category", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("CreatedCategories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Ingredient", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("CreatedIngredients")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.Allergy", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("Allergies")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("Allergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.CommentRating", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("CommentRatings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("CommentRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeCategory", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Category", "Category")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeIngredient", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.RecipeMeal", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Meal", "Meal")
                        .WithMany("RecipeMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeMeals")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.SavedMealPlan", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.MealPlan", "MealPlan")
                        .WithMany("SavedMealPlans")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("SavedMealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MappingEntities.SavedRecipe", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Meal", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.MealPlanDay", "MealPlanDay")
                        .WithMany("Meals")
                        .HasForeignKey("MealPlanDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlanDay");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlan", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("CreatedMealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlanDay", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.MealPlan", "MealPlan")
                        .WithMany("MealPlanDays")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Recipe", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", "User")
                        .WithMany("CreatedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HealthyRecipes.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("CommentRatings");

                    b.Navigation("CreatedCategories");

                    b.Navigation("CreatedIngredients");

                    b.Navigation("CreatedMealPlans");

                    b.Navigation("CreatedRecipes");

                    b.Navigation("SavedMealPlans");

                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Category", b =>
                {
                    b.Navigation("RecipeCategories");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Meal", b =>
                {
                    b.Navigation("RecipeMeals");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlan", b =>
                {
                    b.Navigation("MealPlanDays");

                    b.Navigation("SavedMealPlans");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.MealPlanDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("HealthyRecipes.Data.Entities.Recipe", b =>
                {
                    b.Navigation("CommentRatings");

                    b.Navigation("RecipeCategories");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeMeals");

                    b.Navigation("SavedRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
